#!/usr/bin/env sh
set -eu

json_flag=""

if [ "$#" -eq 2 ] && [ "$1" = "--json" ]; then
  json_flag="--json"
  shift
fi

if [ "$#" -ne 1 ]; then
  echo "Usage: srcquery [--json] \"<query>\"" >&2
  echo "Example: srcquery --json \"parse markdown headings\"" >&2
  exit 2
fi

srcsearch search -i .srcsearch -q "$1" $json_flag
